// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_runner

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func RunnerResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "name of runner",
				MarkdownDescription: "name of runner",
			},
			"runner_deployment_file": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "runner deployment file path",
				MarkdownDescription: "runner deployment file path",
			},
			"runner_deployment_folder": schema.StringAttribute{
				Required:            true,
				Description:         "runner deployments folder path",
				MarkdownDescription: "runner deployments folder path",
			},
			"url": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "url of runner spec file",
				MarkdownDescription: "url of runner spec file",
			},
		},
	}
}

type RunnerModel struct {
	Name                   types.String `tfsdk:"name"`
	RunnerDeploymentFile   types.String `tfsdk:"runner_deployment_file"`
	RunnerDeploymentFolder types.String `tfsdk:"runner_deployment_folder"`
	Url                    types.String `tfsdk:"url"`
}
